---
ID: "eb93e9c3-45da-4002-a009-c78d3304ce71"
Parent: "e8bd65e1-325d-4b03-b449-9ce5cd61c558"
Template: "e8bd65e1-325d-4b03-b449-9ce5cd61c558"
Path: /sitecore/templates/Project/sugcz/Partial Design Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {E8BD65E1-325D-4B03-B449-9CE5CD61C558}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250319T200806Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\matyas.havel@aricoma.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\matyas.havel@aricoma.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b09d142c-7613-4ad3-bee2-df186e072287"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\matyas.havel@aricoma.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250319T200807Z
